version: "3.8"

name: efrei_projet_db_prod

services:
  back:
    image: docker.nexus.jiveoff.fr/jiveoff/efrei-projet-db-back:master
    tty: true
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "3006:3000"
