version: "3.8"

name: efrei_projet_db_dev

services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file: .env
